"""initial_schema

Revision ID: f0f8f6c6e094
Revises: 
Create Date: 2026-07-18 15:24:56.045574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f8f6c6e094'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_isin'), 'companies', ['isin'], unique=True)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('trading_symbol', sa.String(length=30), nullable=False),
    sa.Column('exchange_symbol', sa.String(length=30), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=False),
    sa.Column('instrument_type', sa.String(length=30), nullable=False),
    sa.Column('market_segment', sa.String(length=30), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('face_value', sa.Float(), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'trading_symbol', name='uq_stock_exchange_symbol')
    )
    op.create_index(op.f('ix_stocks_company_id'), 'stocks', ['company_id'], unique=False)
    op.create_index(op.f('ix_stocks_exchange'), 'stocks', ['exchange'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_instrument_type'), 'stocks', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_stocks_listed'), 'stocks', ['listed'], unique=False)
    op.create_index(op.f('ix_stocks_market_segment'), 'stocks', ['market_segment'], unique=False)
    op.create_index(op.f('ix_stocks_trading_symbol'), 'stocks', ['trading_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_trading_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_market_segment'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_listed'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_instrument_type'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_exchange'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_company_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_isin'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
